### ISSUE TITLE
Fabric 1.20.x

### ISSUE THREAD

**Issue by LWC864** [sebastianbhahn/noNametaggedPeacefulDespawn#2]
Upon running minecraft with the mod an error code is displayed
Incompatible mods found!
_Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 17 with version 21 or later.
More details:
	 - Mod 'NoDespawn' (no_despawn) 1.20.x requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!_

I made sure to update OpenJDK to version 22 and have made sure that there is no other installation

**Comment by sebastianbhahn** [comment]
should be version 21 for minecraft 1.20.5 and up, not 22 (or 21 is what I tested it with).
let me check though. I tested it before, and it worked (or I remember it working), but 1.20-1.20.4 run on java 17 while 1.20.5 and up run on java 21, so I might need to split 1.20.x into two versions.

**Comment by sebastianbhahn** [comment]
tested working with java 21. I don't currently have java 22 installed on my system.
I will release a java 17 version for 1.20-1.20.4, though running 1.20-1.20.4 with java 21 does work.

**Comment by sebastianbhahn** [comment]
I have now uploaded a java 17 version for fabric for 1.20-1.20.4

I uploaded it to curseforge, but if you don't want to wait for it to be approved, you can find it here 
https://github.com/sebastianbhahn/noNametaggedPeacefulDespawn/blob/fabric-1.20-1.20.4-java-17/compiled%20jar/no_despawn-1.20-1.20.4.jar

![github-download-file](https://github.com/user-attachments/assets/b40b61ea-a222-4664-ad7b-88e13ba08572)

(image added because I don't find github's ui to be very intuitive)
